spring.application.name=lgabot

# ===================================================================
# CONFIGURAÇÕES DO ACTUATOR & PROMETHEUS
# ===================================================================

# 1. Ativa explicitamente as probes de Liveness e Readiness
management.endpoint.health.probes.enabled=true

# 2. Expõe apenas os endpoints necessários via HTTP (evita expor o que não deve)
management.endpoints.web.exposure.include=health,prometheus

# 3. Mostra os detalhes da saúde dos componentes (Postgres, Redis) se quiser inspecionar
management.endpoint.health.show-details=always

# 4. Garante que as métricas do Prometheus usem tags limpas e eficientes
management.prometheus.metrics.export.enabled=true