events {
    worker_connections 1024;
}

http {
    upstream lgabot_api {
        server lgabot-api:8080;
    }

    # Redireciona HTTP para HTTPS
    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }

    # Configuração do HTTPS
    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate     /etc/nginx/certs/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/privkey.pem;

        # Bloqueia acesso externo ao Actuator
        location ^~ /actuator {
            deny all;
            return 403;
        }

        # Proxy para a API
        location / {
            proxy_pass http://lgabot_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}